### PR TITLE
Makefile.uk: Fix gcc specific warnings

### LINKED ISSUE #48: Fix `unknown option` warnings when building with `clang`
When building `musl` with `clang`, a lot of `unknown option` warnings get generated:

```
warning: unknown warning option '-Wno-format-contains-nul' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-restrict' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
```

Change the `Makefile.uk` file to add the flags only if the compiler used is `gcc`.

Hackathon points: 30

### PR DESCRIPTION
**Pull request by mbrdg**
Re-open after a force push to update the commit message.
Related to #50.

Signed-off-by: Miguel Rodrigues [migb.rodrigues@gmail.com](mailto:migb.rodrigues@gmail.com)

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by eduardvintila — COMMENTED** [review]
Thank you, @mbrdg! This PR gets rid of the warnings, great job! However, it would be great if you could update the commit description with a message such as:


> `-Wno-restrict`, `Wno-unused-but-set-variable`, `-Wno-maybe-unitialized` and `-Wno-format-contains-nul` are gcc-specific flags, so include them only when compiling with `gcc` and not with `clang`.

**Comment by mbrdg** [comment]
Just added the description in the commit!

**Comment by razvand** [comment]
> Just added the description in the commit!

Thanks, @mbrdg. @eduardvintila , could you please see if it's OK with you, so we can approve it?

**Review by eduardvintila — APPROVED** [review]
Great work, thanks a lot for this, @mbrdg!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
