### PR TITLE
lib-musl: Solve conflicts with uk_signal.

### PR DESCRIPTION
**Pull request by dragosargint**
This PR solves some conflicts between the musl library and uk_signal. Since some functions are defined in both musl and uk_signal it leads to a conflict that causes the build to fail.  This PR excludes the sources that cause these errors and also adds uk_singal by default when linking with musl.

This PR is part of a group that aims to solve compiling errors for both musl and newlib:
* https://github.com/unikraft/lib-newlib/pull/15
* https://github.com/unikraft/lib-musl/pull/4
* https://github.com/unikraft/unikraft/pull/327
* https://github.com/unikraft/unikraft/pull/326

### CODE REVIEW

**Review by craciunoiuc — CHANGES_REQUESTED** [review]
Hey @marcrittinghaus,

I think you should review/approve this also, as it's grouped with the other PRs.

I tried it out and the change worked. I couldn't run the image (it stalls), but it didn't work without it either, I guess the stall is musl-related.

@dragosargint please reformat the commit message adding the required `selector` and some additional description

**Review by craciunoiuc — APPROVED** [review]
Hey @marcrittinghaus @dragosargint,

I think the PR looks good now. I don't have extensive knowledge into Musl, but I think it's okay.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Review by marcrittinghaus — CHANGES_REQUESTED** [review]
Hi @dragosargint, 

I think this whole PR series is going into the wrong direction. 

It includes changes that are not related to signals (such as the `prlimit.c` exclusion and many others).

However, a much greater concern is that I think we should prefer the `musl` definitions and exclude the `uksignal` definitions whenever possible. For example, `sig_interrupt` is implemented in `musl` while `uksignal` only has a stub. The same for `alarm` and `pause`. It also makes sense to use the sigset functions of `musl` as applications will use its definition of `__sigset_t`. So I would rather exclude definitions in `uksignal`.

This actually raises the question, if the changes to the `__sigset` type are actually necessary in `lib-newlib` and `nolibc`. As discussed in the community meeting, this needs a rework of `uksignal` first with the goal that `uksignal` takes whatever definitions the used c library provides and not the other way round.

**Comment by razvand** [comment]
This is superseded.

**Pull request closed without merging**
