### PR TITLE
patches: Delete patching of `ioctl` call in `isatty`

### PR DESCRIPTION
**Pull request by mogasergiu**
Application such as `python3` use `isatty()`, which does an `ioctl()` with `TIOCGWINSZ` as an argument for checking whether it should invoke the interactive interpretor or just start interpreting a given file.

Therefore, we may want to allow such function call to return an error if called upon a file from a non-pseudo filesystem such as `ramfs` or `9pfs`.

Furthermore, since this patch is the middle one among the existing patches from an order standpoint, rename the starting index of the other patches to reflect the removal.

This PR depends on `Unikraft Core Repository` [`PR 981`](https://github.com/unikraft/unikraft/pull/981)

### CODE REVIEW

**Review by RaduNichita — APPROVED** [review]
I tested with `app-python3` and it builds and runs on both `x86_64` and `aarch64`

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by StefanJum — APPROVED** [review]
Finally we can run a script using `python3`, thanks @mogasergiu :rocket: :rocket: 
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvanvirtan — APPROVED** [review]
All good, thanks @mogasergiu !
Reviewed-by: Razvan Virtan <virtanrazvan@gmail.com>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Pull request closed without merging**
